### ISSUE TITLE
R 0.50-a4 segfaults

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/evercran#1]
At startup:
```
R : Copyright 1997, Robert Gentleman and Ross Ihaka
Version 0.50 Alpha-4 (September 10, 1997)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type "license()" for details.


Program received signal SIGSEGV, Segmentation fault.
0xf7d921b0 in strcmp () from /lib/tls/libc.so.6
(gdb) bt
#0  0xf7d921b0 in strcmp () from /lib/tls/libc.so.6
#1  0x08079c93 in mkChar ()
#2  0x08060fad in do_strsplit ()
#3  0x0808b7da in do_internal ()
#4  0x0807c20a in eval ()
#5  0x0807d3b4 in do_begin ()
#6  0x0807c20a in eval ()
#7  0x0807c6f3 in applyClosure ()
#8  0x0807c3da in eval ()
#9  0x0807e44e in DispatchOrEval ()
#10 0x0805cee5 in do_c ()
#11 0x0807c20a in eval ()
#12 0x0807e44e in DispatchOrEval ()
#13 0x0805cee5 in do_c ()
#14 0x0807c20a in eval ()
#15 0x0807dcca in evalList ()
#16 0x0807c292 in eval ()
#17 0x0807d9db in do_set ()
#18 0x0807c20a in eval ()
#19 0x08084674 in InitGlobalEnv ()
#20 0x080848ef in mainloop ()
#21 0x080d5d7a in main ()
```

**Comment by gaborcsardi** [comment]
Fixed now, at least R starts.
